### ISSUE TITLE
一个细枝末节的问题

### ISSUE THREAD

**Issue by xiaoyv404** [jxr2006/Arkf#15]
开头的info的右半部分错位了(附截图)
![image](https://user-images.githubusercontent.com/63290381/140619058-5dfc51ca-8579-411b-9863-80b9f5a22de8.png)

**Comment by jxr2006** [comment]
emm，你用CMD就可以了

**Comment by xiaoyv404** [comment]
> emm，你用CMD就可以了

就是cmd（

**Comment by jxr2006** [comment]
> > emm，你用CMD就可以了
> 
> 就是cmd（

那你这cmd有点独特（，强迫症的话自己去程序里面改吧，你这和安卓是一样的，把os.name=='nt'换成!=

**Comment by xiaoyv404** [comment]
> > > emm，你用CMD就可以了
> > 
> > 
> > 就是cmd（
> 
> 那你这cmd有点独特（，强迫症的话自己去程序里面改吧，你这和安卓是一样的，把os.name=='nt'换成!=
确实（
刑
