### ISSUE TITLE
关于2.2.1.10

### ISSUE THREAD

**Issue by Shadowsuki** [jxr2006/Arkf#19]
认证无法覆盖
<img width="960" alt="屏幕快照 2021-11-08 下午7 56 54" src="https://user-images.githubusercontent.com/90943988/140955460-2b95b4ba-60fd-4881-b7f1-57f96ac04e66.png"
代码报错
<img width="566" alt="屏幕快照 2021-11-08 下午7 52 49" src="https://user-images.githubusercontent.com/90943988/140955778-731773fd-7855-4bda-ac39-c33ad37b5853.png">
认证后自动登录会报模糊
<img width="959" alt="屏幕快照 2021-11-08 下午7 48 46" src="https://user-images.githubusercontent.com/90943988/140955703-5d98b69b-ba0f-4e8b-8e3c-6cf69a617aef.png">
模糊时的output
<img width="517" alt="屏幕快照 2021-11-08 下午8 00 04" src="https://user-images.githubusercontent.com/90943988/140955844-098bb3e2-4b78-4b31-b494-1c94de0df9b0.png">

**Comment by xiaoyv404** [comment]
作者最近有点忙，估计是程序出bug了，请把第一个截图下面的的堆栈追踪发一下

**Comment by xiaoyv404** [comment]
是官服吗

**Comment by Shadowsuki** [comment]
> 是官服吗

是
