### ISSUE TITLE
官服防沉迷无法破解

### ISSUE THREAD

**Issue by lucose** [jxr2006/Arkf#6]
21.11.1官服更新后无法破解防沉迷  似乎本地化了 抓不到包

**Comment by Rain0Jack** [comment]
> 21.11.1官服更新后无法破解防沉迷 似乎本地化了 抓不到包

可能是不走代理，目前目前还没解决方法

**Comment by jxr2006** [comment]
抓的到了，不过会记忆模糊

**Comment by AndrewLiu000** [comment]
记忆模糊是指？
